import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from macro_data import get_macro_anchors  # import the external macro pipeline


class marketdatacollector:
    def __init__(self, tickers: list, start_date: str, end_date: str):
        self.tickers = tickers
        self.start_date = start_date
        self.end_date = end_date
        self.scalers = {}

    def fetch_data(self) -> pd.DataFrame:
        processed_dfs = []

        # fetch macro data once for all tickers to save api calls
        macro_df = get_macro_anchors(self.start_date)

        # strip any timezone data so it merges cleanly with yfinance dates
        macro_df['date'] = pd.to_datetime(macro_df['date']).dt.tz_localize(None)

        for ticker in self.tickers:
            # use yf.ticker().history() to guarantee a flat, single-level column index
            stock = yf.Ticker(ticker)
            df = stock.history(start=self.start_date, end=self.end_date)

            if df.empty:
                continue

            df = df.copy()
            df['ticker'] = ticker

            # fetch historical earnings dates safely
            try:
                earnings_df = stock.get_earnings_dates(limit=100)
                if earnings_df is not None and not earnings_df.empty:
                    # strip timezones and normalize to pure dates
                    earnings_dates = earnings_df.index.tz_localize(None).normalize()
                else:
                    earnings_dates = []
            except Exception:
                # fallback to empty array if data is missing for this ticker
                earnings_dates = []

            # yfinance index is timezone-aware, strip it for merging
            df.index = df.index.tz_localize(None)
            df.reset_index(inplace=True)
            df.rename(columns={'Date': 'date'}, inplace=True)

            # engineer past observed features
            df['returns'] = df['Close'].pct_change()
            df['volatility_7d'] = df['returns'].rolling(window=7).std()

            # rsi calculation
            delta = df['Close'].diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
            rs = gain / loss
            df['rsi_14'] = 100 - (100 / (1 + rs))

            # engineer the earnings binary flag
            df['is_earnings_day'] = 0
            if len(earnings_dates) > 0:
                df.loc[df['date'].dt.normalize().isin(earnings_dates), 'is_earnings_day'] = 1

            # merge the macro data (inner join aligns trading days exactly)
            df = pd.merge(df, macro_df, on='date', how='inner')

            # engineer known future calendar features using the new date column
            df['day_of_week'] = df['date'].dt.dayofweek
            df['month'] = df['date'].dt.month
            df['day_of_month'] = df['date'].dt.day

            # set date back to index for downstream model requirements
            df.set_index('date', inplace=True)

            # drop nan values generated by rolling windows
            df.dropna(inplace=True)
            processed_dfs.append(df)

        return pd.concat(processed_dfs)

    def scale_features(self, df: pd.DataFrame, features_to_scale: list) -> pd.DataFrame:
        scaled_df = df.copy()

        # force all target columns to float64 to accept minmaxscaler outputs
        scaled_df[features_to_scale] = scaled_df[features_to_scale].astype(float)

        for ticker in df['ticker'].unique():
            mask = scaled_df['ticker'] == ticker
            scaler = MinMaxScaler()
            scaled_df.loc[mask, features_to_scale] = scaler.fit_transform(
                scaled_df.loc[mask, features_to_scale]
            )
            self.scalers[ticker] = scaler

        return scaled_df