import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler


class marketdatacollector:
    def __init__(self, tickers: list, start_date: str, end_date: str):
        self.tickers = tickers
        self.start_date = start_date
        self.end_date = end_date
        self.scalers = {}

    def fetch_data(self) -> pd.DataFrame:
        processed_dfs = []

        for ticker in self.tickers:
            # use yf.ticker().history() to guarantee a flat, single-level column index
            stock = yf.Ticker(ticker)
            df = stock.history(start=self.start_date, end=self.end_date)

            if df.empty:
                continue

            df = df.copy()
            df['ticker'] = ticker

            # engineer past observed features
            df['returns'] = df['Close'].pct_change()
            df['volatility_7d'] = df['returns'].rolling(window=7).std()

            # rsi calculation
            delta = df['Close'].diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
            rs = gain / loss
            df['rsi_14'] = 100 - (100 / (1 + rs))

            # engineer known future calendar features
            df['day_of_week'] = df.index.dayofweek
            df['month'] = df.index.month
            df['day_of_month'] = df.index.day

            # drop nan values generated by rolling windows
            df.dropna(inplace=True)
            processed_dfs.append(df)

        return pd.concat(processed_dfs)

    def scale_features(self, df: pd.DataFrame, features_to_scale: list) -> pd.DataFrame:
        scaled_df = df.copy()

        # force all target columns to float64 to accept minmaxscaler outputs
        scaled_df[features_to_scale] = scaled_df[features_to_scale].astype(float)

        for ticker in df['ticker'].unique():
            mask = scaled_df['ticker'] == ticker
            scaler = MinMaxScaler()
            scaled_df.loc[mask, features_to_scale] = scaler.fit_transform(
                scaled_df.loc[mask, features_to_scale]
            )
            self.scalers[ticker] = scaler

        return scaled_df