import torch
import torch.nn as nn
from .grn import gatedresidualnetwork


class interpretablemultiheadattention(nn.Module):
    def __init__(self, hidden_size: int, num_heads: int, dropout_rate: float = 0.1):
        super().__init__()

        self.num_heads = num_heads
        self.hidden_size = hidden_size

        # pytorch native multihead attention
        self.attention = nn.MultiheadAttention(
            embed_dim=hidden_size,
            num_heads=num_heads,
            dropout=dropout_rate,
            batch_first=True
        )

        # final processing layer after attention is applied
        self.post_attention_grn = gatedresidualnetwork(
            input_size=hidden_size,
            hidden_size=hidden_size,
            output_size=hidden_size,
            dropout_rate=dropout_rate
        )

        self.layer_norm = nn.LayerNorm(hidden_size)

    def forward(self, temporal_features, attention_context):
        # temporal_features shape: (batch, time_steps, hidden_size)
        # attention_context shape: (batch, hidden_size) -> generated by static encoder

        # expand context vector to match the time dimension for the queries
        time_steps = temporal_features.size(1)
        expanded_context = attention_context.unsqueeze(1).expand(-1, time_steps, -1).contiguous()

        # perform attention operations
        # keys and values come from the temporal history; queries are guided by static context
        attn_output, attn_weights = self.attention(
            query=expanded_context,
            key=temporal_features,
            value=temporal_features,
            need_weights=True
        )

        # apply residual connection, layer norm, and final gating
        attn_output = self.layer_norm(attn_output + temporal_features)
        output = self.post_attention_grn(attn_output)

        return output, attn_weights